name: WorldSigns
main: me.VetBakSim.worldsigns.Main
version: 1.0
author: VetBakSim
website: http://www.kipnetwork.net/

permissions:
  worldsigns.remove:
    default: op
  worldsigns.add:
    default: op
  worldsigns.zone.1:
    default: op
  worldsigns.zone.2:
    default: op
  worldsigns.zone.3:
    default: op
  worldsigns.zone.4:
    default: op